### ISSUE TITLE
swiss horizon not working anymore 

### ISSUE THREAD

**Issue by bendschs** [DeBaschdi/service.takealug.epg-grabber#15]
takealug stopped working for me a couple of days ago. the log shows a http error. i tried to reach the url and it does not seem to be available any longer. 

can i manually point takealug to the right url?

cheers
bendsch

```
2022-10-15 01:04:32.525 T:8655  WARNING <general>: RunScript called for a non-script addon 'service.takealug.epg-grabber'. This behaviour is deprecated.
2022-10-15 01:04:32.526 T:9858     INFO <general>: initializing python engine.
2022-10-15 01:04:35.927 T:9858    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 404 Client Error: Not Found for url: https://obo-prod.oesp.upctv.ch/oesp/v2/CH/deu/web/channels
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/service.takealug.epg-grabber/service.py", line 574, in <module>
                                                       run_grabber()
                                                     File "/home/pi/.kodi/addons/service.takealug.epg-grabber/service.py", line 198, in run_grabber
                                                       if horizon.startup('ch'):
                                                     File "/home/pi/.kodi/addons/service.takealug.epg-grabber/resources/providers/horizon.py", line 586, in startup
                                                       get_channellist(grabber, hzndict, hzn_chlist_provider_tmp, hzn_chlist_provider)
                                                     File "/home/pi/.kodi/addons/service.takealug.epg-grabber/resources/providers/horizon.py", line 136, in get_channellist
                                                       hzn_chlist_url.raise_for_status()
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://obo-prod.oesp.upctv.ch/oesp/v2/CH/deu/web/channels
                                                   -->End of Python script error report<--
                                                   
2022-10-15 01:04:36.431 T:9858     INFO <general>: Python interpreter stopped

```

**Comment by DeBaschdi** [comment]
Unfortunately it's not that easy
there have been major API changes within individual countries, calls need to be reassessed.

**Comment by bendschs** [comment]
ok, would you recommend to move to another swiss provider, like zattoo?

**Comment by DeBaschdi** [comment]
I would always prefer swisscom over horizon ^^
